# FILE: render.yaml
# LOCATION: news/render.yaml
# PURPOSE: Tells Render how to deploy the news service
# SERVICE: News analyzer web service

services:
  - type: web
    name: news-analyzer
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: NEWS_API_KEY
        sync: false
      - key: GOOGLE_FACT_CHECK_API_KEY
        sync: false
