# FILE: render.yaml
# LOCATION: news/render.yaml
# PURPOSE: Render deployment configuration with Python 3.11

services:
  - type: web
    name: news-analyzer
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
