services:
  - type: web
    name: news-analyzer
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: pro
    region: oregon
    envVars:
      # Python settings
      - key: PYTHON_VERSION
        value: "3.11.0"
      - key: WEB_CONCURRENCY
        value: "2"
      
      # API Keys (set these in Render dashboard for security)
      # - key: OPENAI_API_KEY
      #   sync: false
      # - key: GOOGLE_FACT_CHECK_API_KEY
      #   sync: false
      # - key: NEWS_API_KEY
      #   sync: false
      # - key: SERPAPI_KEY
      #   sync: false
      # - key: SCRAPERAPI_KEY
      #   sync: false
      # - key: SCRAPINGBEE_API_KEY
      #   sync: false
      # - key: MEDIASTACK_API_KEY
      #   sync: false
      # - key: FRED_API_KEY
      #   sync: false
      
    buildCommand: ""  # Build is handled by Dockerfile
    startCommand: ""  # Start command is in Dockerfile CMD
    healthCheckPath: /health
    autoDeploy: false  # Set to true if you want auto-deploy on git push
